# -*- mode: ruby -*-
# vi: set ft=ruby :

$configureMasterNodeBox = <<-SCRIPT
  #LFS258
  apt-get update
  apt-get upgrade -y
  apt-get install -y docker.io

  add-apt-repository 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  apt-get update
  apt-get install -y kubeadm kubelet kubectl

  IP_ADDR=`ifconfig enp0s8 | grep Mask | awk '{print $2}'| cut -f2 -d:`
  echo "$IP_ADDR k8smaster" >> /etc/hosts

  swapoff -a
  sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

  #this part taken from https://github.com/ecomm-integration-ballerina/kubernetes-cluster/blob/master/Vagrantfile
  IP_ADDR=`ifconfig enp0s8 | grep Mask | awk '{print $2}'| cut -f2 -d:`
  HOST_NAME=$(hostname -s) 
  kubeadm init --apiserver-advertise-address=$IP_ADDR --apiserver-cert-extra-sans=$IP_ADDR  --node-name $HOST_NAME --pod-network-cidr=172.16.0.0/16
SCRIPT

$kubectl = <<-SCRIPT
  #prepare kubectl
  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
  source <(kubectl completion bash)
  echo "source <(kubectl completion bash)" >> ~/.bashrc

  #install calico
  wget https://tinyurl.com/yb4xturm -O rbac-kdd.yaml
  kubectl apply -f rbac-kdd.yaml

  wget https://tinyurl.com/y8lvqc9g -O calico.yaml
  kubectl apply -f calico.yaml
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "master-node"
  config.vm.network :private_network, ip: "10.0.0.10"

  config.vm.provision "shell", inline: $configureMasterNodeBox
  config.vm.provision "shell", inline: $kubectl, privileged: false
end
